### ISSUE TITLE
Custom pickler leads to exception while compiling java.lang.IndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by mariussoutier** [lihaoyi/upickle#160]
As soon as I add an `object MyPickler extends upickle.AttributeTagged` the project no longer compiles with error message `(uiClient/compile:compileIncremental) java.lang.IndexOutOfBoundsException: 0`.

When I comment it out, everything goes back to normal.

Stack trace:

``` scala
java.lang.IndexOutOfBoundsException: 0
    at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
    at scala.collection.immutable.List.apply(List.scala:84)
    at xsbt.ExtractAPI.makeParameter$1(ExtractAPI.scala:295)
    at xsbt.ExtractAPI.xsbt$ExtractAPI$$parameterS$1(ExtractAPI.scala:286)
    at xsbt.ExtractAPI$$anonfun$parameterList$1$1.apply(ExtractAPI.scala:225)
    at xsbt.ExtractAPI$$anonfun$parameterList$1$1.apply(ExtractAPI.scala:225)
    at scala.collection.immutable.List.map(List.scala:273)
    at xsbt.ExtractAPI.parameterList$1(ExtractAPI.scala:225)
    at xsbt.ExtractAPI.build$1(ExtractAPI.scala:246)
    at xsbt.ExtractAPI.defDef(ExtractAPI.scala:303)
...
```

This happens in the Scala.js part of a Play project.

**Comment by SkyWriter** [comment]
Seems to have been related to https://github.com/sbt/sbt/issues/2497. Upgrading SBT to 0.13.13+ solved the issue for me.

**Comment by lihaoyi** [comment]
Bug bankruptcy
