### ISSUE TITLE
 java.lang.UnsupportedOperationException: empty.reduceLeft

### ISSUE THREAD

**Issue by nafg** [lihaoyi/upickle#163]
This scenario should give a more helpful error message

```
exception during macro expansion: 
[error] java.lang.UnsupportedOperationException: empty.reduceLeft
[error]     at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
[error]     at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$reduceLeft(ArrayBuffer.scala:48)
[error]     at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
[error]     at scala.collection.mutable.ArrayBuffer.reduceLeft(ArrayBuffer.scala:48)
[error]     at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
[error]     at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
[error]     at upickle.Macros$Reading.mergeTrait(Macros.scala:77)
[error]     at derive.Derive.deriveTrait(Derive.scala:298)
[error]     at derive.Derive$$anonfun$9.apply(Derive.scala:237)
[error]     at derive.Derive$$anonfun$9.apply(Derive.scala:235)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error]     at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error]     at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]     at derive.Derive.deriveType(Derive.scala:235)
[error]     at derive.Derive.derive(Derive.scala:60)
[error]     at upickle.Macros$.macroRImpl(Macros.scala:145)
[error]                 val client: Clients.Ent = read[Clients.Ent](new String(bytes))
[error]                                                            ^
```

**Comment by lihaoyi** [comment]
Bug bankruptcy
