### ISSUE TITLE
upickle case class with more than 22 parameters

### ISSUE THREAD

**Issue by pahlgrimm** [lihaoyi/upickle#167]
Hi, I am creating a case class to interact with the postmark service. So my case class has more than 22 parameters and at compile time I get the following error:
`Error:(24, 16) exception during macro expansion: 
java.lang.IllegalArgumentException: requirement failed: Tuples with 28 arity aren't supported
    at scala.reflect.internal.ReificationSupport$ReificationSupportImpl$SyntacticTupleType$.apply(ReificationSupport.scala:438)
    at scala.reflect.internal.ReificationSupport$ReificationSupportImpl$SyntacticTupleType$.apply(ReificationSupport.scala:436)
    at upickle.Macros$Reading.wrapCaseN(Macros.scala:66)
    at derive.Derive.deriveClass(Derive.scala:344)
    at derive.Derive$$anonfun$9.apply(Derive.scala:239)
    at derive.Derive$$anonfun$9.apply(Derive.scala:235)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at derive.Derive.deriveType(Derive.scala:235)
    at derive.Derive.derive(Derive.scala:60)
    at upickle.Macros$.macroRImpl(Macros.scala:145)
    read[Email](json)`

Is it possible to resolve this or should I think of a workaround?

Thanks for your great work!

**Comment by lihaoyi** [comment]
Bug bankruptcy
