### ISSUE TITLE
Is it possible to read parameterized/polymorphic case classes ?

### ISSUE THREAD

**Issue by l15k4** [lihaoyi/upickle#19]
I'm sorry for flooding upicke with issues :-) But I got utterly stuck on reading : 

```
case class What[E](a: TypeThatHasAReaderAvailable[E])

read[What[Ever]](xyz)
```

The problem is here : 
https://github.com/lihaoyi/upickle/blob/ccd23c491ebec51a091ffc49b709d067fa1c1df8/shared/main/scala/upickle/Macros.scala#L121

```
[info] exception during macro expansion: 
[info] scala.ScalaReflectionException: value apply encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
[info]  at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:228)
[info]  at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:82)
[info]  at upickle.Macros$.picklerFor(Macros.scala:121)
[info]  at upickle.Macros$.macroRImpl(Macros.scala:32)
[info]       val res = read[ResponseMessage[Vertex]](x.data.toString)
[info]   
```

I tried even invoke the macro supplying the type parameters directly to it, but it failed the same way : 

```
    import scala.language.experimental.macros
    def macroR[T]: Reader[T] = macro Macros.macroRImpl[T]
    val a = macroR[What[Ever]]
```

Would you please give me a hint here?

**Comment by ForNeVeR** [comment]
@lihaoyi I think that should be mentioned in the documentation.
