### ISSUE TITLE
upickle fails randomly for nest case class

### ISSUE THREAD

**Issue by kajia** [lihaoyi/upickle#196]
Test with upickle 0.4.4 & Scala 2.12.1

```scala
import org.scalatest._
import upickle.default._

case class InnerCase(m1: Map[String, String] = Map.empty, //if remove this, test will always success, but I need it.
                     //f1: String ="", //uncomment one or more of those fields, test will pass or fail randomly!
                     //f2: String ="",
                     //f3: String ="",
                     //f4: String ="",
                     f5: Int = 1)
sealed trait ST
case class OutCase(i1: Option[InnerCase] = None,
                   b2: Int = 0) extends ST

class TestCase extends FlatSpec with Matchers {
  it should "pickle" in {
    val cc = OutCase(Some(InnerCase()))
    val json = write(cc)
    read[OutCase](json) shouldEqual cc
  }
}
```

```shell
[info] TestCase:
[info] - should pickle *** FAILED ***
[info]   upickle.Invalid$Data: Number or String (data: {})
[info]   at upickle.Implicits$Internal$$anon$1.$anonfun$apply$1(Implicits.scala:83)
[info]   at upickle.Implicits$$anonfun$numericReaderFunc$1.applyOrElse(Implicits.scala:139)
[info]   at upickle.Implicits$$anonfun$numericReaderFunc$1.applyOrElse(Implicits.scala:137)
[info]   at upickle.Implicits$Internal$$anon$1.apply(Implicits.scala:83)
[info]   at upickle.Implicits$Internal$$anon$1.apply(Implicits.scala:80)
[info]   at upickle.Types$Reader$$anon$2.apply(Types.scala:112)
[info]   at upickle.Types$Reader$$anon$2.apply(Types.scala:103)
[info]   at upickle.Types.readJs(Types.scala:160)
[info]   at upickle.Types.readJs$(Types.scala:160)
[info]   at upickle.default$.readJs(Api.scala:25)
[info]   ...
```

**Comment by LogicalTime** [comment]
How about if you make it as Seq[(String,String)] instead of a map. What happens then?

**Comment by colin-passiv** [comment]
I also hit this problem. The issue is with case classes which have an Option of other case classes.
Moving the inner case class about (e.g. defining inside an object) seemed to help.

The issue could be avoided by commenting out the following line, which tries to read the optional value as an `Int`:
https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/shared/src/main/scala/upickle/Implicits.scala#L197
i.e.
`implicit def NoneR: R[None.type] = R[None.type](OptionR[Int].read andThen (_.asInstanceOf[None.type]))`

I guess this line exists to allow to read None for otherwise unreadable values.
Maybe it could be moved to a lower priority trait, to ensure the OptionR[T] is tried first.

**Comment by lihaoyi** [comment]
uPickle's "deep" automatic case-class pickling is gone in 0.5.1
