### ISSUE TITLE
upickle is giving runtime issues when using with scalajs-react 

### ISSUE THREAD

**Issue by ashu2012** [lihaoyi/upickle#250]
Hi,

i compilation is fine but during webpack bundle stage it is giving tones of warninings and during action page load it is giving runtime issues:-

```
`$c_Lujson_ParseException {s$1: "expected json value got N (line 1, column 1) at index 0", e$1: null, stackTrace$1: null, clue$3: "expected json value got N (line 1, column 1)", index$3: 0, …}clue$3: "expected json value got N (line 1, column 1)"col$3: 1e$1: nullindex$3: 0line$3: 1s$1: "expected json value got N (line 1, column 1) at index 0"stackTrace$1: nullstackdata: $c_Lujson_ParseException {s$1: "expected json value got N (line 1, column 1) at index 0", e$1: null, stackTrace$1: null, clue$3: "expected json value got N (line 1, column 1)", index$3: 0, …}stack: "Error↵    at $c_Lujson_ParseException.../../../../js/scalajs-react-template-opt.js.$c_jl_Throwable.fillInStackTrace__jl_Throwable (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:25423:14)↵    at $c_Lujson_ParseException.../../../../js/scalajs-react-template-opt.js.$c_jl_Throwable.init___T__jl_Throwable (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:25445:8)↵    at $c_Lujson_ParseException.../../../../js/scalajs-react-template-opt.js.$c_Lujson_ParseException.init___T__I__I__I (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:59378:52)↵    at $c_Lujson_StringParser.../../../../js/scalajs-react-template-opt.js.$c_Lujson_Parser.die__I__T__sr_Nothing$ (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:16615:40)↵    at $c_Lujson_StringParser.../../../../js/scalajs-react-template-opt.js.$c_Lujson_Parser.parse__I__Lujson_Visitor__T2 (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:16742:14)↵    at $c_Lujson_StringParser.../../../../js/scalajs-react-template-opt.js.$c_Lujson_SyncParser.parse__Lujson_Visitor__O (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:24944:17)↵    at $c_Lujson_StringParser$.../../../../js/scalajs-react-template-opt.js.$c_Lujson_StringParser$.transform__T__Lujson_Visitor__O (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:24912:51)↵    at $c_Lujson_StringParser$.../../../../js/scalajs-react-template-opt.js.$c_Lujson_StringParser$.transform__O__Lujson_Visitor__O (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:24915:15)↵    at $f_Lupickle_Api__read__Lujson_Transformable__Lupickle_core_Types$BaseReader__O (http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:59408:16)↵    at http://localhost:12345/target/scala-2.12/scalajs-bundler/main/scalajs-react-template-opt-bundle.js:15722:74"__proto__: $c_jl_Exception
../../../../js/scalajs-react-template-opt.js.$c_Lujson_Parser.parse__I__Lujson_Visitor__T2 @ Parser.scala:352
../../../../js/scalajs-react-template-opt.js.$c_Lujson_SyncParser.parse__Lujson_Visitor__O @ SyncParser.scala:23
../../../../js/scalajs-react-template-opt.js.$c_Lujson_StringParser$.transform__T__Lujson_Visitor__O @ StringParser.scala:28
../../../../js/scalajs-react-template-opt.js.$c_Lujson_StringParser$.transform__O__Lujson_Visitor__O @ StringParser.scala:27
$f_Lupickle_Api__read__Lujson_Transformable__Lupickle_core_Types$BaseReader__O @ Transformable.scala:13
(anonymous) @ Api.scala:66
../../../../js/scalajs-react-template-opt.js.$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15
(anonymous) @ Builder.scala:154
../../../../js/scalajs-react-template-opt.js.$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15
(anonymous) @ ViaReactComponent.scala:269
../../../../js/scalajs-react-template-opt.js.$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15
(anonymous) @ ViaReactComponent.scala:216
(anonymous) @ ReactCompositeComponent.js:796
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:795
_renderValidatedComponent @ ReactCompositeComponent.js:822
performInitialMount @ ReactCompositeComponent.js:362
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialChildren @ ReactDOMComponent.js:697
mountComponent @ ReactDOMComponent.js:516
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountComponentIntoNode @ ReactMount.js:104
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
$f_Ljapgolly_scalajs_react_component_Generic$UnmountedSimple__renderIntoDOM__sjs_js_$bar__F0__O @ Generic.scala:80
../../../../js/scalajs-react-template-opt.js.$c_Lscalajsreact_template_ReactApp$.main__V @ Js.scala:66
(anonymous) @ scalajs-react-template-opt-bundle.js:75660
../../../../js/scalajs-react-template-opt.js @ scalajs-react-template-opt-bundle.js:75662
__webpack_require__ @ bootstrap:19
0 @ global.js:20
__webpack_require__ @ bootstrap:19
../../../../js/scalajs-react-template-opt.js.$env @ bootstrap:83
(anonymous) @ bootstrap:83
2ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$63f2bo60oo7' of null
    at Object.getClosestInstanceFromNode (ReactDOMComponentTree.js:113)
    at findParent (ReactEventListener.js:38)
    at handleTopLevelImpl (ReactEventListener.js:67)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:140)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.batchedUpdates (ReactUpdates.js:97)
    at dispatchEvent (ReactEventListener.js:147)
getClosestInstanceFromNode @ ReactDOMComponentTree.js:113
findParent @ ReactEventListener.js:38
handleTopLevelImpl @ ReactEventListener.js:67
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
load (async)
listen @ EventListener.js:29
trapBubbledEvent @ ReactEventListener.js:113
trapBubbledEvent @ ReactBrowserEventEmitter.js:283
trapBubbledEventsLocal @ ReactDOMComponent.js:279
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:148
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
$f_Ljapgolly_scalajs_react_component_Generic$UnmountedSimple__renderIntoDOM__sjs_js_$bar__F0__O @ Generic.scala:80
../../../../js/scalajs-react-template-opt.js.$c_Lscalajsreact_template_ReactApp$.main__V @ Js.scala:66
(anonymous) @ scalajs-react-template-opt-bundle.js:75660
../../../../js/scalajs-react-template-opt.js @ scalajs-react-template-opt-bundle.js:75662
__webpack_require__ @ bootstrap:19
0 @ global.js:20
__webpack_require__ @ bootstrap:19
../../../../js/scalajs-react-template-opt.js.$env @ bootstrap:83
(anonymous) @ bootstrap:83`
```

sbt fastOptJS::webpack output:-

````

warn] Module Warning (from ./node_modules/source-map-loader/index.js):
[warn] (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src-js/ujson/Platform.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src-js/ujson/Platform.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn] NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src-js/ujson/Platform.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src-js/ujson/Platform.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn]     at emitWarning (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\webpack\lib\NormalModule.js:154:16)
[warn]     at C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\source-map-loader\index.js:74:7
[warn]     at doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at resolver.doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
[warn]     at resolver.doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn42 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:393:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn1 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn1 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at fs.stat (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:22:13)
[warn]     at process.nextTick (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:73:15)
[warn]     at process._tickCallback (internal/process/next_tick.js:61:11)
[warn]  @ multi C:/Users/h217119/IdeaProjects/ScalaJsWebApp/js/scalajs-react-template-opt.js scalajs-react-template-opt[0]
[warn] C:/Users/h217119/IdeaProjects/ScalaJsWebApp/js/scalajs-react-template-opt.js
[warn] Module Warning (from ./node_modules/source-map-loader/index.js):
[warn] (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CharBasedParser.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CharBasedParser.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn] NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CharBasedParser.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CharBasedParser.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn]     at emitWarning (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\webpack\lib\NormalModule.js:154:16)
[warn]     at C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\source-map-loader\index.js:74:7
[warn]     at doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at resolver.doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
[warn]     at resolver.doResolve (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn42 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:393:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn1 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn1 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
[warn]     at hook.callAsync (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
[warn]     at _fn0 (eval at create (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
[warn]     at fs.stat (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:22:13)
[warn]     at process.nextTick (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:73:15)
[warn]     at process._tickCallback (internal/process/next_tick.js:61:11)
[warn]  @ multi C:/Users/h217119/IdeaProjects/ScalaJsWebApp/js/scalajs-react-template-opt.js scalajs-react-template-opt[0]
[warn] C:/Users/h217119/IdeaProjects/ScalaJsWebApp/js/scalajs-react-template-opt.js
[warn] Module Warning (from ./node_modules/source-map-loader/index.js):
[warn] (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CustomVisitor.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CustomVisitor.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn] NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CustomVisitor.scala': Error: Can't resolve '../../../../../../Users/lihaoyi/Dropbox/Github/upickle/ujson/src/ujson/CustomVisitor.scala' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp\js'
[warn]     at emitWarning (C:\Users\h217119\IdeaProjects\ScalaJsWebApp\target\scala-2.12\scalajs-bundler\main\node_modules\webpack\lib\NormalModule.js:154:16)
`

```

**Comment by ashu2012** [comment]
scalaVersion := "2.12.2"

// create launcher file ( its search for object extends JSApp , make sure there is only one file)
//persistLauncher := true
//persistLauncher in Test := false

val scalaJSReactVersion = "1.3.1"
val scalaCssVersion     = "0.5.5"
val reactJSVersion      = "16.5.1"

**Comment by axos88** [comment]
+1

**Comment by axos88** [comment]
@lihaoyi

**Comment by axos88** [comment]
This is still the case with scala 2.12.8, scalajs 0.6.26

**Comment by lihaoyi** [comment]
closing as invalid, as the report has zero use to anyone trying to triage this. If anyone has a better repro, feel free to open a new issue.
