### ISSUE TITLE
Stackoverflow exception

### ISSUE THREAD

**Issue by eakarsu** [lihaoyi/upickle#290]
I am getting this exception. Any clue on why it happens?

19/12/16 13:37:10 ERROR Executor: Exception in task 5.0 in stage 0.0 (TID 5)
java.lang.StackOverflowError
	at ujson.AstTransformer.transformArray(AstTransformer.scala:10)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)
	at ujson.AstTransformer.$anonfun$transformArray$1(AstTransformer.scala:11)
	at ujson.AstTransformer.$anonfun$transformArray$1$adapted(AstTransformer.scala:11)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ujson.AstTransformer.transformArray(AstTransformer.scala:11)
	at ujson.AstTransformer.transformArray$(AstTransformer.scala:9)
	at ujson.Value$.transformArray(Value.scala:123)
	at ujson.Value$.transform(Value.scala:188)
	at ujson.Value$.transform(Value.scala:123)

**Comment by eakarsu** [comment]
This is my error. I was building incorrect json document with ujson and paring it.

**Comment by eakarsu** [comment]
Closing it
