### ISSUE TITLE
An Implementation is missing at runtime

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/upickle#38]
Hi, 
I use upickle through autowire in a scalatra client/server application.
My server depends on JVM stuff (for autowire, upickle, ...) and my client one on JS stuff (for autowire, upickle, ...). 

Everything compiles and runs fine, except when I do a request through autowire, I get a weird exeception when upickle reads the JSON data. Is some lib or something is missing ?
Thanks

``` sh
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
    at scala.scalajs.js.JSON$.parse$default$2(JSON.scala:33)
    at upickle.json.package$.read(package.scala:20)
    at upickle.Types$class.read(Types.scala:135)
    at upickle.package$.read(package.scala:10)
    at org.openmole.gui.server.core.GUIServlet$$anonfun$2.apply(GUIServlet.scala:69)
    at org.openmole.gui.server.core.GUIServlet$$anonfun$2.apply(GUIServlet.scala:65)
```

**Comment by ShengC** [comment]
I had similar issue - turns out it is because jvm depends on js, which brings in all dependencies of js to jvm which includes js version of upickle. You can use projectDependencies to explicitly exclude js upickle from the classpath of jvm.
